import { getAccessToken } from '../lib/googleAuth';

export interface DriveFileItem {
  id: string;
  name: string;
  mimeType: string;
  size?: string;
  createdTime?: string;
  modifiedTime?: string;
  webViewLink?: string;
  webContentLink?: string;
  iconLink?: string;
  parents?: string[];
  thumbnailLink?: string;
}

export interface DriveFolder {
  id: string;
  name: string;
}

/**
 * Creates or retrieves a folder in Google Drive by name.
 */
export async function getOrCreateFolder(
  folderName: string,
  parentId?: string
): Promise<string> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  // Search if folder already exists
  let q = `mimeType='application/vnd.google-apps.folder' and name='${folderName.replace(/'/g, "\\'")}' and trashed=false`;
  if (parentId) {
    q += ` and '${parentId}' in parents`;
  }

  const searchRes = await fetch(
    `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)`,
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );

  if (!searchRes.ok) {
    const err = await searchRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to search Google Drive folders');
  }

  const searchData = await searchRes.json();
  if (searchData.files && searchData.files.length > 0) {
    return searchData.files[0].id;
  }

  // Create folder if not found
  const metadata: { name: string; mimeType: string; parents?: string[] } = {
    name: folderName,
    mimeType: 'application/vnd.google-apps.folder',
  };
  if (parentId) {
    metadata.parents = [parentId];
  }

  const createRes = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(metadata),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create folder in Google Drive');
  }

  const createdData = await createRes.json();
  return createdData.id;
}

/**
 * Uploads a text or JSON file into Google Drive.
 */
export async function uploadTextFileToDrive({
  fileName,
  content,
  mimeType = 'application/json',
  folderId,
  description,
}: {
  fileName: string;
  content: string;
  mimeType?: string;
  folderId?: string;
  description?: string;
}): Promise<DriveFileItem> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  const metadata: any = {
    name: fileName,
    mimeType: mimeType,
    description: description || 'Generated by LNNCHS Multi-Sync Educational Hub',
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}; charset=UTF-8\r\n\r\n` +
    content +
    closeDelimiter;

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,createdTime,modifiedTime,webViewLink,webContentLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: multipartRequestBody,
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to upload ${fileName} to Google Drive`);
  }

  return await res.json();
}

/**
 * Uploads a binary Blob (PDF, Excel, Word, Image) into Google Drive.
 */
export async function uploadBlobToDrive({
  fileName,
  blob,
  mimeType,
  folderId,
  description,
}: {
  fileName: string;
  blob: Blob;
  mimeType: string;
  folderId?: string;
  description?: string;
}): Promise<DriveFileItem> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  const metadata: any = {
    name: fileName,
    mimeType: mimeType,
    description: description || 'Exported from LNNCHS Multi-Sync Hub',
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  const form = new FormData();
  form.append(
    'metadata',
    new Blob([JSON.stringify(metadata)], { type: 'application/json' })
  );
  form.append('file', blob);

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,createdTime,modifiedTime,webViewLink,webContentLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
      },
      body: form,
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to upload ${fileName} to Google Drive`);
  }

  return await res.json();
}

/**
 * Lists files and folders from Google Drive.
 */
export async function listDriveFiles(options?: {
  folderId?: string;
  pageSize?: number;
  searchQuery?: string;
}): Promise<DriveFileItem[]> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  let q = 'trashed=false';
  if (options?.folderId) {
    q += ` and '${options.folderId}' in parents`;
  }
  if (options?.searchQuery && options.searchQuery.trim()) {
    q += ` and name contains '${options.searchQuery.trim().replace(/'/g, "\\'")}'`;
  }

  const pageSize = options?.pageSize || 40;
  const fields =
    'files(id,name,mimeType,size,createdTime,modifiedTime,webViewLink,webContentLink,thumbnailLink,iconLink,parents)';

  const res = await fetch(
    `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      q
    )}&pageSize=${pageSize}&orderBy=modifiedTime desc&fields=${encodeURIComponent(
      fields
    )}`,
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to list Google Drive files');
  }

  const data = await res.json();
  return data.files || [];
}

/**
 * Deletes a file from Google Drive (DESTRUCTIVE OPERATION).
 * Note: Must always be preceded by explicit user confirmation modal.
 */
export async function deleteDriveFile(fileId: string): Promise<boolean> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}`, {
    method: 'DELETE',
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok && res.status !== 204) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to delete file from Google Drive');
  }

  return true;
}

/**
 * Shares a file or folder with a specific email address (e.g. operativecreative@gmail.com).
 */
export async function shareDriveFileWithEmail(
  fileId: string,
  emailAddress: string,
  role: 'reader' | 'commenter' | 'writer' = 'writer'
): Promise<boolean> {
  const token = await getAccessToken();
  if (!token) throw new Error('Authentication required. Please sign in with Google.');

  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}/permissions`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      role: role,
      type: 'user',
      emailAddress: emailAddress,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to share file with ${emailAddress}`);
  }

  return true;
}

export async function getDriveStorageInfo(): Promise<{
  limit?: string;
  usage?: string;
  usageInDrive?: string;
  usageInDriveTrash?: string;
}> {
  const token = await getAccessToken();
  if (!token) return {};

  const res = await fetch('https://www.googleapis.com/drive/v3/about?fields=storageQuota,user', {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok) return {};
  const data = await res.json();
  return data.storageQuota || {};
}
