import React, { useState, useEffect } from 'react';
import {
  FileText,
  Presentation,
  FileSpreadsheet,
  KeyRound,
  Download,
  Copy,
  Check,
  Printer,
  ShieldCheck,
  Sparkles,
  ArrowLeft,
  Lock,
  ChevronLeft,
  ChevronRight,
  Maximize2,
  Minimize2,
  CheckCircle2,
  AlertTriangle,
  FileDown,
  Loader2,
  Share2,
  Award,
  BookOpen,
  ExternalLink,
  GraduationCap
} from 'lucide-react';
import { ILAWCompletePlan, ILAWSlide } from '../types/ilawDO3';
import { exportDO3ILAWToDocx } from '../utils/depedDocxExporter';
import { exportDO3ILAWToPptx } from '../utils/depedPptxExporter';
import { exportDO3ILAWToPdf } from '../utils/depedPdfExporter';
import { exportActivityCheckerToXlsx } from '../utils/excelActivityCheckerExporter';
import { DO3ILAWView } from './DO3ILAWView';
import { StandaloneAnswerKeysView } from './StandaloneAnswerKeysView';
import { ExcelActivityChecker } from './ExcelActivityChecker';

interface MyILAWGeneratedSectionProps {
  plan: ILAWCompletePlan;
  onNavigateToForm: () => void;
}

export const MyILAWGeneratedSection: React.FC<MyILAWGeneratedSectionProps> = ({
  plan,
  onNavigateToForm
}) => {
  const [activeTab, setActiveTab] = useState<'matrix' | 'slides' | 'las' | 'grading'>('matrix');
  const [activeGradingSubTab, setActiveGradingSubTab] = useState<'answers' | 'checker' | 'guidelines'>('answers');
  const [activeSlideIndex, setActiveSlideIndex] = useState<number>(0);
  const [isFullscreenSlide, setIsFullscreenSlide] = useState<boolean>(false);
  const [activeLasIndex, setActiveLasIndex] = useState<number>(0);

  // Export states
  const [isExportingDocx, setIsExportingDocx] = useState(false);
  const [isExportingPptx, setIsExportingPptx] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  const { header, matrix, activitySheets, presentationSlides } = plan;

  const activityCheckerMeta = {
    school: header.school,
    subject: header.learningArea,
    gradeAndSection: header.gradeLevelAndSection,
    teacher: header.teacher,
    term: `Term ${header.term}`,
    week: header.bowWeek,
    topic: header.lesson,
    dates: header.inclusiveTeachingDates,
    maxScores: {
      las1: 25,
      las2: 25,
      las3: 25,
      las4: 25
    }
  };

  const handleExportDocx = async () => {
    try {
      setIsExportingDocx(true);
      await exportDO3ILAWToDocx(plan);
      setStatusMessage('✓ Word Document (.docx) successfully downloaded!');
      setTimeout(() => setStatusMessage(null), 4000);
    } catch (e) {
      console.error('Docx export error', e);
      setStatusMessage('Export failed. Please check browser permissions.');
    } finally {
      setIsExportingDocx(false);
    }
  };

  const handleExportPptx = async () => {
    try {
      setIsExportingPptx(true);
      await exportDO3ILAWToPptx(plan);
      setStatusMessage('✓ PowerPoint Companion Deck (.pptx) successfully downloaded!');
      setTimeout(() => setStatusMessage(null), 4000);
    } catch (e) {
      console.error('Pptx export error', e);
      setStatusMessage('PPT export failed.');
    } finally {
      setIsExportingPptx(false);
    }
  };

  const handleExportPdf = async () => {
    try {
      setIsExportingPdf(true);
      await exportDO3ILAWToPdf(plan);
      setStatusMessage('✓ DepEd DO 3, s. 2026 PDF successfully downloaded!');
      setTimeout(() => setStatusMessage(null), 4000);
    } catch (e) {
      console.error('PDF export error', e);
      setStatusMessage('PDF export failed.');
    } finally {
      setIsExportingPdf(false);
    }
  };

  const handleCopyPPTLink = () => {
    const text = `DepEd Order No. 3, s. 2026 Auto-Generated Companion PPT Deck\n` +
      `Subject: ${header.learningArea}\n` +
      `Topic: ${header.lesson}\n` +
      `Teacher: ${header.teacher}\n` +
      `School: ${header.school}\n` +
      `Slides: 12 Widescreen Slides (Body Font >= 35pt Projection Verified)\n` +
      `Inclusive Dates: ${header.inclusiveTeachingDates}\n` +
      `Generated by Boiser Education Platform.`;
    navigator.clipboard.writeText(text).then(() => {
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2500);
    });
  };

  // Keyboard navigation for interactive slides
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (activeTab === 'slides') {
        if (e.key === 'ArrowRight' || e.key === 'Space') {
          setActiveSlideIndex((prev) => Math.min(presentationSlides.length - 1, prev + 1));
        } else if (e.key === 'ArrowLeft') {
          setActiveSlideIndex((prev) => Math.max(0, prev - 1));
        } else if (e.key === 'Escape' && isFullscreenSlide) {
          setIsFullscreenSlide(false);
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [activeTab, presentationSlides.length, isFullscreenSlide]);

  const curSlide = presentationSlides[activeSlideIndex] || presentationSlides[0];
  const curSheet = activitySheets[activeLasIndex] || activitySheets[0];

  return (
    <div className="space-y-6 animate-fade-in pb-16">
      {/* 1. MANDATORY SAFEGUARD BANNER: Form Inputs Locked */}
      <div className="bg-amber-50 border-2 border-amber-300 rounded-3xl p-4 sm:p-5 shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-start sm:items-center gap-3.5">
          <div className="w-10 h-10 rounded-2xl bg-amber-500 text-stone-950 flex items-center justify-center shrink-0 shadow-xs">
            <Lock className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-extrabold text-amber-950 uppercase tracking-wide">
                Input Form Locked — Finalized Read-Only Output Section
              </h2>
              <span className="px-2 py-0.5 rounded-full bg-amber-200 text-amber-900 text-[10px] font-bold">
                DO 3, s. 2026 Compliant
              </span>
            </div>
            <p className="text-xs text-amber-900 mt-0.5 max-w-2xl leading-relaxed">
              Form inputs and curriculum parameters are locked to prevent accidental edits while viewing, presenting, printing, or exporting your lesson plan and grading resources.
            </p>
          </div>
        </div>

        <button
          onClick={onNavigateToForm}
          className="px-4 py-2 rounded-xl bg-white hover:bg-stone-50 text-[#0038A8] border border-stone-300 text-xs font-bold transition flex items-center gap-2 shadow-xs shrink-0 cursor-pointer"
          title="Return to the 9-field input form if you need to modify teaching parameters or competencies"
        >
          <ArrowLeft className="w-4 h-4 text-[#0038A8]" />
          <span>Edit in ILAW Form</span>
        </button>
      </div>

      {/* Notification Toast */}
      {statusMessage && (
        <div className="bg-emerald-50 border border-emerald-300 text-emerald-900 p-3 rounded-2xl text-xs font-bold flex items-center gap-2 shadow-xs">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{statusMessage}</span>
        </div>
      )}

      {/* 2. Top Banner: Finalized Lesson Plan Header Summary */}
      <div className="bg-gradient-to-r from-[#002776] via-[#0038A8] to-[#001c54] text-white rounded-3xl p-6 sm:p-8 shadow-md border-b-4 border-[#FCD116] space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full bg-[#CE1126] text-white text-xs font-bold uppercase tracking-wider flex items-center gap-1.5 shadow-xs">
              <Sparkles className="w-3.5 h-3.5 text-[#FCD116]" />
              Official DepEd Exemplar Master
            </span>
            <span className="text-xs text-blue-100 font-medium">
              Region X • LNNCHS Standards
            </span>
          </div>

          <div className="flex items-center gap-2 text-xs">
            <span className="px-3 py-1 rounded-full bg-[#FCD116] text-[#002776] font-bold shadow-xs flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5 text-[#002776]" />
              Verified Authentic BOW Data
            </span>
          </div>
        </div>

        <div className="space-y-2">
          <h1 className="text-2xl sm:text-3xl font-extrabold font-serif tracking-tight text-white">
            My ILAW Generated Lesson Plan
          </h1>
          <div className="flex flex-wrap items-center gap-2 text-xs text-blue-100">
            <span className="bg-white/10 px-2.5 py-1 rounded-lg border border-white/15 font-semibold text-white">
              {header.learningArea}
            </span>
            <span>•</span>
            <span className="font-bold text-[#FCD116]">{header.lesson}</span>
            <span>•</span>
            <span>{header.gradeLevelAndSection}</span>
            <span>•</span>
            <span>Term {header.term} ({header.inclusiveTeachingDates})</span>
            <span>•</span>
            <span>Teacher: {header.teacher}</span>
          </div>
        </div>

        {/* Global Export & Actions Toolbar */}
        <div className="pt-2 flex flex-wrap items-center gap-2.5">
          {/* PPT Direct Download Link Button */}
          <button
            onClick={handleExportPptx}
            disabled={isExportingPptx}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#FCD116] hover:bg-amber-300 text-[#002776] text-xs font-bold transition shadow-xs cursor-pointer disabled:opacity-50"
            title="Download auto-generated PowerPoint companion deck (.pptx) with >=35pt typography"
          >
            {isExportingPptx ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Presentation className="w-4 h-4 text-[#002776]" />
            )}
            <span>{isExportingPptx ? 'Exporting PPT...' : 'Download Auto-Generated PPT (.pptx)'}</span>
            <span className="px-1.5 py-0.2 rounded bg-amber-400/80 text-[10px] font-extrabold text-[#002776]">
              &ge;35pt
            </span>
          </button>

          {/* Word Export */}
          <button
            onClick={handleExportDocx}
            disabled={isExportingDocx}
            className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-white hover:bg-stone-100 text-[#002776] text-xs font-bold transition shadow-xs cursor-pointer disabled:opacity-50"
            title="Download complete 4-part official Word document (.docx)"
          >
            {isExportingDocx ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <FileText className="w-4 h-4 text-[#002776]" />
            )}
            <span>{isExportingDocx ? 'Exporting Word...' : 'Download Word (.docx)'}</span>
          </button>

          {/* PDF Export */}
          <button
            onClick={handleExportPdf}
            disabled={isExportingPdf}
            className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-blue-900 hover:bg-blue-950 text-white border border-blue-400/40 text-xs font-bold transition shadow-xs cursor-pointer disabled:opacity-50"
            title="Export high-fidelity DepEd A4 printable PDF document"
          >
            {isExportingPdf ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <FileDown className="w-4 h-4 text-[#FCD116]" />
            )}
            <span>{isExportingPdf ? 'Exporting PDF...' : 'Download DepEd PDF (.pdf)'}</span>
          </button>

          {/* Excel Checker Download */}
          <button
            onClick={() => exportActivityCheckerToXlsx([], activityCheckerMeta)}
            className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition shadow-xs cursor-pointer"
            title="Download formula-enabled Excel Activity Checker (.xlsx)"
          >
            <FileSpreadsheet className="w-4 h-4" />
            <span>Excel Activity Checker (.xlsx)</span>
          </button>

          {/* Copy PPT Link */}
          <button
            onClick={handleCopyPPTLink}
            className="flex items-center gap-1.5 px-3 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition cursor-pointer border border-white/20"
            title="Copy PPT Deck link and metadata to clipboard"
          >
            {copiedLink ? <Check className="w-4 h-4 text-emerald-400" /> : <Share2 className="w-4 h-4" />}
            <span>{copiedLink ? 'Copied Link!' : 'Copy PPT Info'}</span>
          </button>

          {/* Print */}
          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition cursor-pointer border border-white/20"
          >
            <Printer className="w-4 h-4" />
            <span>Print All</span>
          </button>
        </div>
      </div>

      {/* 3. Primary Output Navigation Tabs */}
      <div className="bg-white rounded-3xl p-3 border border-stone-200 shadow-xs flex flex-wrap items-center gap-2">
        <button
          onClick={() => setActiveTab('matrix')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-2xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'matrix'
              ? 'bg-[#002776] text-white shadow-xs'
              : 'text-stone-700 hover:bg-stone-100'
          }`}
        >
          <FileText className={`w-4 h-4 ${activeTab === 'matrix' ? 'text-[#FCD116]' : 'text-[#002776]'}`} />
          <span>Part 1 &amp; 2: Finalized Lesson Plan Matrix</span>
        </button>

        <button
          onClick={() => setActiveTab('slides')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-2xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'slides'
              ? 'bg-[#002776] text-white shadow-xs'
              : 'text-stone-700 hover:bg-stone-100'
          }`}
        >
          <Presentation className={`w-4 h-4 ${activeTab === 'slides' ? 'text-[#FCD116]' : 'text-[#002776]'}`} />
          <span>Part 4: Auto-Generated PPT Presentation Deck</span>
          <span className="px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-900 text-[10px] font-extrabold">
            12 Slides • &ge;35pt
          </span>
        </button>

        <button
          onClick={() => setActiveTab('las')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-2xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'las'
              ? 'bg-[#002776] text-white shadow-xs'
              : 'text-stone-700 hover:bg-stone-100'
          }`}
        >
          <FileSpreadsheet className={`w-4 h-4 ${activeTab === 'las' ? 'text-[#FCD116]' : 'text-[#002776]'}`} />
          <span>Part 3: Learning Activity Sheets (LAS 1–4)</span>
          <span className="px-2 py-0.5 rounded-full bg-amber-100 text-amber-900 text-[10px] font-extrabold">
            {activitySheets.length} Authentic Sheets
          </span>
        </button>

        <button
          onClick={() => setActiveTab('grading')}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-2xl text-xs font-bold transition cursor-pointer ${
            activeTab === 'grading'
              ? 'bg-amber-600 text-white shadow-xs'
              : 'text-amber-900 hover:bg-amber-50'
          }`}
        >
          <KeyRound className="w-4 h-4 text-amber-300" />
          <span>Grading Resources &amp; Teacher Keys</span>
          <span className="px-2 py-0.5 rounded-full bg-amber-200 text-amber-950 text-[10px] font-extrabold">
            DO 015 Tools
          </span>
        </button>
      </div>

      {/* 4. TAB 1: FINALIZED LESSON PLAN MATRIX */}
      {activeTab === 'matrix' && (
        <div className="space-y-6">
          <DO3ILAWView
            plan={plan}
            onExportDocx={handleExportDocx}
            onExportPptx={handleExportPptx}
            onExportPdf={handleExportPdf}
            isExportingDocx={isExportingDocx}
            isExportingPptx={isExportingPptx}
            isExportingPdf={isExportingPdf}
          />
        </div>
      )}

      {/* 5. TAB 2: AUTO-GENERATED PPT PRESENTATION DECK & LINK */}
      {activeTab === 'slides' && (
        <div className="space-y-6">
          {/* PPT Direct Action & Link Card */}
          <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white rounded-3xl p-6 sm:p-7 border border-indigo-700/50 shadow-md space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 rounded-md bg-[#FCD116] text-[#002776] text-[11px] font-extrabold uppercase tracking-wide">
                    Live Auto-Generated Deck
                  </span>
                  <span className="text-xs text-indigo-200">
                    DepEd Order No. 3, s. 2026 Companion Resource
                  </span>
                </div>
                <h3 className="text-xl font-bold font-serif text-white">
                  Presentation Deck: {header.lesson}
                </h3>
                <p className="text-xs text-slate-300">
                  Formatted strictly with &ge;35pt typography for classroom display projectors and smart screens.
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-2 shrink-0">
                <button
                  onClick={handleExportPptx}
                  disabled={isExportingPptx}
                  className="px-4 py-2.5 rounded-xl bg-[#FCD116] hover:bg-amber-300 text-[#002776] font-extrabold text-xs transition flex items-center gap-2 shadow-xs cursor-pointer"
                >
                  <Download className="w-4 h-4" />
                  <span>Download .pptx File</span>
                </button>

                <button
                  onClick={handleCopyPPTLink}
                  className="px-3.5 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-white font-bold text-xs transition flex items-center gap-1.5 border border-white/20 cursor-pointer"
                >
                  {copiedLink ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  <span>{copiedLink ? 'Copied!' : 'Copy PPT Specs'}</span>
                </button>

                <button
                  onClick={() => setIsFullscreenSlide(!isFullscreenSlide)}
                  className="px-3.5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs transition flex items-center gap-1.5 cursor-pointer"
                  title="Toggle fullscreen projector mode"
                >
                  {isFullscreenSlide ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
                  <span>{isFullscreenSlide ? 'Exit Projector' : 'Projector Mode'}</span>
                </button>
              </div>
            </div>

            {/* Slide Quick Navigation Thumbnails */}
            <div className="pt-2 border-t border-slate-700/60 flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
              {presentationSlides.map((s, idx) => (
                <button
                  key={s.slideNumber}
                  onClick={() => setActiveSlideIndex(idx)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold shrink-0 transition cursor-pointer flex items-center gap-1.5 ${
                    activeSlideIndex === idx
                      ? 'bg-[#FCD116] text-[#002776] shadow-xs'
                      : 'bg-white/10 text-slate-300 hover:bg-white/20'
                  }`}
                >
                  <span>Slide {s.slideNumber}</span>
                  <span className="text-[10px] opacity-75 truncate max-w-[100px]">{s.badge}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Interactive Slide Viewer Container */}
          <div
            className={`transition-all rounded-3xl overflow-hidden border-2 border-slate-800 bg-[#0A1128] text-white shadow-xl ${
              isFullscreenSlide ? 'fixed inset-0 z-50 rounded-none m-0 p-8 flex flex-col justify-between bg-[#0A1128]' : 'p-6 sm:p-10 space-y-6'
            }`}
          >
            {/* Slide Top Bar */}
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2.5">
                <span className="px-3 py-1 rounded-md bg-[#0038A8] text-[#FCD116] text-xs font-extrabold tracking-wider uppercase border border-blue-500/40">
                  {curSlide.badge || `SLIDE ${curSlide.slideNumber}`}
                </span>
                <span className="text-xs text-slate-400 font-medium hidden sm:inline">
                  {header.school} • DepEd DO 3, s. 2026
                </span>
              </div>

              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-amber-400">
                  Slide {curSlide.slideNumber} of {presentationSlides.length}
                </span>
                {isFullscreenSlide && (
                  <button
                    onClick={() => setIsFullscreenSlide(false)}
                    className="p-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white cursor-pointer ml-2"
                  >
                    <Minimize2 className="w-4 h-4" />
                  </button>
                )}
              </div>
            </div>

            {/* Slide Content Area - High Contrast Typography (>=35pt equivalent) */}
            <div className="space-y-6 max-w-4xl mx-auto my-4 sm:my-8 text-center sm:text-left">
              <h2 className="text-2xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight">
                {curSlide.title}
              </h2>

              {curSlide.subtitle && (
                <p className="text-base sm:text-xl text-slate-300 italic">
                  {curSlide.subtitle}
                </p>
              )}

              {/* Body Bullets Card */}
              <div className="bg-[#131F42] border border-slate-700/80 rounded-2xl p-6 sm:p-8 space-y-4 shadow-lg text-left">
                <div className="flex items-center gap-2 text-xs font-bold text-[#FCD116] uppercase tracking-wider pb-2 border-b border-slate-800">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Key Discussion Points (&ge;35pt Body Text Certified)</span>
                </div>

                <ul className="space-y-4">
                  {curSlide.bodyBullets.map((bullet, bIdx) => (
                    <li key={bIdx} className="flex items-start gap-3">
                      <span className="w-2.5 h-2.5 rounded-full bg-[#FCD116] shrink-0 mt-2.5"></span>
                      <span className="text-lg sm:text-2xl font-medium text-white leading-relaxed">
                        {bullet}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Teacher Speaker Notes */}
              {curSlide.speakerNotes && (
                <div className="bg-blue-950/60 border border-blue-800/40 rounded-xl p-4 text-left">
                  <span className="text-[11px] font-bold text-blue-300 uppercase tracking-wide block mb-1">
                    Presenter Notes:
                  </span>
                  <p className="text-xs sm:text-sm text-blue-100">
                    {curSlide.speakerNotes}
                  </p>
                </div>
              )}
            </div>

            {/* Slide Controls Footer */}
            <div className="flex items-center justify-between pt-4 border-t border-slate-800">
              <button
                onClick={() => setActiveSlideIndex((prev) => Math.max(0, prev - 1))}
                disabled={activeSlideIndex === 0}
                className="px-4 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-bold transition flex items-center gap-1.5 disabled:opacity-30 cursor-pointer"
              >
                <ChevronLeft className="w-4 h-4" />
                <span>Previous Slide</span>
              </button>

              <div className="flex items-center gap-1.5 text-xs text-slate-400">
                <span>Tip: Use keyboard</span>
                <kbd className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-300 font-mono text-[10px]">Left</kbd>
                <span>/</span>
                <kbd className="px-1.5 py-0.5 rounded bg-slate-800 text-slate-300 font-mono text-[10px]">Right</kbd>
                <span>arrows to navigate</span>
              </div>

              <button
                onClick={() => setActiveSlideIndex((prev) => Math.min(presentationSlides.length - 1, prev + 1))}
                disabled={activeSlideIndex === presentationSlides.length - 1}
                className="px-4 py-2 rounded-xl bg-[#0038A8] hover:bg-blue-700 text-white text-xs font-bold transition flex items-center gap-1.5 disabled:opacity-30 cursor-pointer"
              >
                <span>Next Slide</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 6. TAB 3: LEARNING ACTIVITY SHEETS (LAS 1–4) */}
      {activeTab === 'las' && (
        <div className="space-y-6">
          {/* LAS Selector Bar */}
          <div className="bg-white rounded-3xl p-4 border border-stone-200 shadow-xs flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2 overflow-x-auto">
              {activitySheets.map((sheet, idx) => (
                <button
                  key={sheet.sessionNumber}
                  onClick={() => setActiveLasIndex(idx)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition cursor-pointer flex items-center gap-2 ${
                    activeLasIndex === idx
                      ? 'bg-[#002776] text-white shadow-xs'
                      : 'bg-stone-100 text-stone-700 hover:bg-stone-200'
                  }`}
                >
                  <FileSpreadsheet className="w-4 h-4" />
                  <span>LAS {sheet.sessionNumber}</span>
                  <span className="text-[10px] opacity-80 hidden sm:inline">({sheet.sessionDate})</span>
                </button>
              ))}
            </div>

            <button
              onClick={() => window.print()}
              className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition flex items-center gap-1.5 shadow-xs cursor-pointer"
              title="Print student worksheet copies for distribution"
            >
              <Printer className="w-4 h-4" />
              <span>Print Student Worksheet (LAS {curSheet.sessionNumber})</span>
            </button>
          </div>

          {/* Active LAS View Container */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200 shadow-sm space-y-6">
            {/* Sheet Header */}
            <div className="border-b-2 border-stone-200 pb-4 text-center space-y-1">
              <p className="text-[11px] font-bold text-stone-500 uppercase tracking-widest">
                Republic of the Philippines • Department of Education
              </p>
              <p className="text-xs font-bold text-stone-700">
                {header.region} • {header.division}
              </p>
              <h2 className="text-xl font-bold font-serif text-[#002776]">
                LEARNING ACTIVITY SHEET NO. {curSheet.sessionNumber}
              </h2>
              <p className="text-sm font-semibold text-stone-800">
                {curSheet.activityTitle}
              </p>
            </div>

            {/* Student Info Bar */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-3 rounded-xl bg-stone-50 border border-stone-200 text-xs">
              <div>
                <strong className="text-stone-600">Pangalan:</strong> ____________________________
              </div>
              <div>
                <strong className="text-stone-600">Baitang at Pangkat:</strong> {header.gradeLevelAndSection}
              </div>
              <div>
                <strong className="text-stone-600">Petsa:</strong> {curSheet.sessionDate}
              </div>
            </div>

            {/* Objectives & Materials */}
            <div className="space-y-4 text-xs leading-relaxed text-stone-800">
              <div className="p-3.5 rounded-xl bg-blue-50 border border-blue-200">
                <strong className="text-[#002776] block mb-1">Mga Layunin sa Pagkatuto (Learning Objectives):</strong>
                <ul className="list-disc list-inside space-y-1 text-stone-700">
                  {curSheet.objectives.map((obj, i) => (
                    <li key={i}>{obj}</li>
                  ))}
                </ul>
              </div>

              <div className="space-y-1.5">
                <h4 className="font-bold text-stone-900 uppercase tracking-wide">
                  I. Mga Kagamitan at Panuto (Materials &amp; Instructions):
                </h4>
                <div className="p-3.5 rounded-xl bg-stone-50 border border-stone-200 text-stone-700 space-y-1">
                  <p><strong>Mga Kagamitan:</strong> {curSheet.materials.join(', ')}</p>
                  <p><strong>Pangkalahatang Panuto:</strong> {curSheet.instruction}</p>
                </div>
              </div>

              {/* Tasks */}
              <div className="space-y-4 pt-2">
                <h4 className="font-bold text-stone-900 uppercase tracking-wide">
                  II. Mga Gawain at Pagsasanay (Exercises / Activities):
                </h4>

                {/* Part A: Collaborative Group Task */}
                <div className="p-4 rounded-xl border border-stone-200 space-y-3 bg-white">
                  <div className="flex items-center justify-between font-bold text-stone-900 text-sm">
                    <span>Gawain A: {curSheet.partAGroup.title}</span>
                    <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-100 text-[#0038A8] font-bold">
                      Format: {curSheet.partAGroup.formatType}
                    </span>
                  </div>
                  <p className="text-stone-700">{curSheet.partAGroup.scenarioOrPrompt}</p>

                  {curSheet.partAGroup.tableData && (
                    <div className="overflow-x-auto my-2">
                      <table className="w-full text-xs border border-stone-300">
                        <thead className="bg-stone-100">
                          <tr>
                            {curSheet.partAGroup.tableData.headers.map((h, hi) => (
                              <th key={hi} className="p-2 border border-stone-300 text-left font-bold">{h}</th>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {curSheet.partAGroup.tableData.rows.map((row, ri) => (
                            <tr key={ri}>
                              {row.map((cell, ci) => (
                                <td key={ci} className="p-2 border border-stone-300">{cell}</td>
                              ))}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}

                  {curSheet.partAGroup.guidingQuestions.length > 0 && (
                    <div className="space-y-1 pt-1">
                      <span className="font-bold text-stone-800">Mga Gabay na Tanong:</span>
                      <ul className="list-decimal list-inside space-y-1 text-stone-600">
                        {curSheet.partAGroup.guidingQuestions.map((q, qi) => (
                          <li key={qi}>{q}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>

                {/* Part B: Individual Written Task */}
                <div className="p-4 rounded-xl border border-stone-200 space-y-3 bg-white">
                  <div className="flex items-center justify-between font-bold text-stone-900 text-sm">
                    <span>Gawain B: {curSheet.partBIndividual.title}</span>
                    <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-100 text-emerald-900 font-bold">
                      Output: {curSheet.partBIndividual.outputType}
                    </span>
                  </div>
                  <p className="text-stone-700">{curSheet.partBIndividual.taskPrompt}</p>

                  {curSheet.partBIndividual.analysisChallenge.length > 0 && (
                    <div className="space-y-1 pt-1">
                      <span className="font-bold text-stone-800">Hamon sa Pagsusuri (Analysis Challenge):</span>
                      <ul className="list-disc list-inside space-y-1 text-stone-600">
                        {curSheet.partBIndividual.analysisChallenge.map((ac, ai) => (
                          <li key={ai}>{ac}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </div>

              {/* Analytic Rubric */}
              <div className="space-y-2 pt-3">
                <h4 className="font-bold text-stone-900 uppercase tracking-wide">
                  IV. Pamantayan sa Pagmamarka (Analytic Rubric — 4-Point Scale):
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-[11px] border border-stone-300">
                    <thead className="bg-[#002776] text-white">
                      <tr>
                        <th className="p-2 border border-stone-300 text-left w-1/4">Pamantayan</th>
                        <th className="p-2 border border-stone-300 text-center">Napakahusay (4)</th>
                        <th className="p-2 border border-stone-300 text-center">Mahusay (3)</th>
                        <th className="p-2 border border-stone-300 text-center">Umuunlad (2)</th>
                        <th className="p-2 border border-stone-300 text-center">Nagsisimula (1)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {curSheet.rubric.criteria.map((c, ci) => (
                        <tr key={ci} className={ci % 2 === 0 ? 'bg-white' : 'bg-stone-50'}>
                          <td className="p-2 border border-stone-300 font-bold text-stone-800">{c.criterion}</td>
                          <td className="p-2 border border-stone-300 text-stone-600">{c.exemplary4}</td>
                          <td className="p-2 border border-stone-300 text-stone-600">{c.proficient3}</td>
                          <td className="p-2 border border-stone-300 text-stone-600">{c.developing2}</td>
                          <td className="p-2 border border-stone-300 text-stone-600">{c.beginning1}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 7. TAB 4: GRADING RESOURCES (ANSWER KEYS & EXCEL CHECKER) */}
      {activeTab === 'grading' && (
        <div className="space-y-6">
          {/* Grading Sub-tabs */}
          <div className="inline-flex p-1 rounded-2xl bg-stone-200/80 border border-stone-300 text-xs flex-wrap gap-1">
            <button
              onClick={() => setActiveGradingSubTab('answers')}
              className={`px-4 py-2 rounded-xl font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeGradingSubTab === 'answers'
                  ? 'bg-amber-600 text-white shadow-xs'
                  : 'text-stone-700 hover:text-stone-950'
              }`}
            >
              <KeyRound className="w-3.5 h-3.5" />
              <span>Standalone Teacher Answer Keys</span>
            </button>

            <button
              onClick={() => setActiveGradingSubTab('checker')}
              className={`px-4 py-2 rounded-xl font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeGradingSubTab === 'checker'
                  ? 'bg-emerald-700 text-white shadow-xs'
                  : 'text-stone-700 hover:text-stone-950'
              }`}
            >
              <FileSpreadsheet className="w-3.5 h-3.5" />
              <span>Interactive Excel Activity Checker</span>
            </button>

            <button
              onClick={() => setActiveGradingSubTab('guidelines')}
              className={`px-4 py-2 rounded-xl font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeGradingSubTab === 'guidelines'
                  ? 'bg-[#002776] text-white shadow-xs'
                  : 'text-stone-700 hover:text-stone-950'
              }`}
            >
              <GraduationCap className="w-3.5 h-3.5" />
              <span>DO 015, s. 2026 Grading Weightings</span>
            </button>
          </div>

          {activeGradingSubTab === 'answers' && (
            <StandaloneAnswerKeysView plan={plan} />
          )}

          {activeGradingSubTab === 'checker' && (
            <ExcelActivityChecker meta={activityCheckerMeta} />
          )}

          {activeGradingSubTab === 'guidelines' && (
            <div className="bg-white rounded-3xl p-6 sm:p-8 border border-stone-200 shadow-sm space-y-6">
              <div className="flex items-center gap-3 pb-3 border-b border-stone-200">
                <div className="w-10 h-10 rounded-2xl bg-[#0038A8] text-white flex items-center justify-center font-bold">
                  DO
                </div>
                <div>
                  <h3 className="text-base font-bold text-stone-900">
                    DepEd Order No. 015, s. 2026: Strengthened Senior High School Assessment Matrix
                  </h3>
                  <p className="text-xs text-stone-500">
                    Three-Term (Trimester) Weighted Percentages for Written Works &amp; Performance Tasks
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="p-4 rounded-2xl bg-blue-50 border border-blue-200 space-y-2">
                  <h4 className="font-bold text-[#002776] text-sm flex items-center gap-1.5">
                    <Award className="w-4 h-4 text-[#002776]" />
                    Academic Track Weightings
                  </h4>
                  <p className="text-stone-700">Applies to General Mathematics, General Science, and Effective Communication:</p>
                  <ul className="space-y-1.5 text-stone-800 font-medium">
                    <li className="flex justify-between border-b border-blue-200 pb-1">
                      <span>Written Works (WW):</span>
                      <strong>30%</strong>
                    </li>
                    <li className="flex justify-between border-b border-blue-200 pb-1">
                      <span>Performance Tasks (PT) [incl. LAS Outputs]:</span>
                      <strong>50%</strong>
                    </li>
                    <li className="flex justify-between">
                      <span>Quarterly/Term Assessment (QA):</span>
                      <strong>20%</strong>
                    </li>
                  </ul>
                </div>

                <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 space-y-2">
                  <h4 className="font-bold text-emerald-900 text-sm flex items-center gap-1.5">
                    <Award className="w-4 h-4 text-emerald-700" />
                    TechPro Track Weightings
                  </h4>
                  <p className="text-stone-700">Applies to TechPro &amp; Career Disciplines (Hands-on mastery):</p>
                  <ul className="space-y-1.5 text-stone-800 font-medium">
                    <li className="flex justify-between border-b border-emerald-200 pb-1">
                      <span>Written Works (WW):</span>
                      <strong>20%</strong>
                    </li>
                    <li className="flex justify-between border-b border-emerald-200 pb-1">
                      <span>Performance Tasks (PT) [Lab/Shop Works]:</span>
                      <strong>60%</strong>
                    </li>
                    <li className="flex justify-between">
                      <span>Quarterly/Term Assessment (QA):</span>
                      <strong>20%</strong>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200 text-xs text-stone-700 space-y-2">
                <h5 className="font-bold text-stone-900">DepEd Transmutation Formula:</h5>
                <p>
                  Initial Grade = (Learner Total Raw Score &divide; Highest Possible Score) &times; 100. Transmuted Grade is computed using the official DepEd Transmutation Table where an Initial Grade of 60.00 translates to the passing grade of 75.
                </p>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
